name: NEW1 CI/CD Workflow

on:
  workflow_call:
    inputs:
      selected_repo:
        description: 'The selected repository for the workflow'
        required: true
        default: 'turbo5000c/tomcat-root-war'
      detected_language:
        description: 'Detected programming language of the source code'
        required: true
      file_upload:
        description: 'File to upload'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    inputs:
      tag_name:
        description: 'Tag name for the workflow'
        required: true

    outputs:
      build_status:
        description: 'Status of the build process'
      test_status:
        description: 'Status of the test process'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        run: echo 'Setting up environment based on detected technologies'

      - name: Build
        run: echo 'Building the project with tag ${{ inputs.tag_name }}'
        id: build
        continue-on-error: true

      - name: Test
        run: echo 'Running tests for the project'
        id: test
        continue-on-error: true

      - name: Upload File
        run: echo 'Uploading file: ${{ inputs.file_upload }}'
        continue-on-error: true

      - name: Set Build Status
        run: echo "::set-output name=build_status::${{ job.status }}"

      - name: Set Test Status
        run: echo "::set-output name=test_status::${{ job.status }}"