name: Generic Build

on:
  workflow_call:
    secrets:
      token:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build placeholder
      run: |
        echo 'Add your build steps here'
        echo 'This is a generic template - customize based on your project needs'
    - name: Test placeholder
      run: |
        echo 'Add your test steps here'
        echo 'Configure your specific testing framework and commands'

  container_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build -t your_image_tag .