name: UNJT RX Build

on:
  workflow_call:
    secrets:
      token:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "running rebuild"
