name: Main CI

on:
  push:
    paths-ignore:
      - '.github/workflows/**'


jobs:
  use-reusable-workflow:
    uses: ./.github/workflows/AM_XITB_reusable-build.yml
    with:
      node-version: '20'
      run-tests: true